spring:
  application:
    name: hbaseputter

hbase:
  zookeeper:
    quorum: "bdmaster1.kodit.co.kr:2181,bdmaster2.kodit.co.kr:2181,bdmaster3.kodit.co.kr:2181"
    znode: "/hbase-unsecure"
  table:
    name: "kjg_test_table"
    cf: "cf1"
    columnName: "image"



app:
  image:
    path: "classpath:images/test.png"