spring:
  application:
    name: hbaseputter

hbase:
  zookeeper:
    quorum: "dsdmma1.datastreams.co.kr:2181,dsdmma2.datastreams.co.kr:2181,dsdmma3.datastreams.co.kr:2181"
    znode: "/hbase-unsecure"
  table:
    name: "kjg_test_table"
    cf: "cf1"
    columnName: "image"



app:
  image:
    path: "classpath:images/test.png"