spring:
  application:
    name: hbaseputter

hbase:
  zookeeper:
    quorum: "10.194.1.34:2181,10.194.1.35:2181,10.194.1.36:2181"
  table:
    name: "kjg_test_table"
    cf: "cf1"

app:
  image:
    path: "classpath:images/test.png"